export CUDA_VISIBLE_DEVICES=6
python main.py \
--seed 0 \
--drop_out \
--early_stopping \
--lr 1e-5 \
--k_start 3 \
--k 5 \
--label_frac 1 \
--bag_loss ce \
--task task_3_pt_staging_cls2 \
--results_dir results/Yifuyuan_new \
--exp_code task_3_pt_staging_20x_10x_SAMF_cls2_BLCA_mp \
--model_type patch_gcn \
--mode graph \
--log_data \
--data_root_dir /home1/sjb/gastric_cancer/pt_staging/our_work_yfy/DATA_ROOT_DIR/BLCA \
--data_folder_s gastric_pt_staging_20x \
--data_folder_l gastric_pt_staging_10x \
--tg_file tissue_graph_files_slic \
--split_dir /home1/sjb/gastric_cancer/pt_staging/our_work_SAMF/splits/BLCA/task_3_pt_staging_cls2_100 \
